#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

def transform(text):
  text=text.lower()
  text = text.replace("z ","üz")
  text = text.replace("z.","üz.")
  text = text.replace("z!","üz!")
  text = text.replace("aí","ani")
  text = text.replace("o ","oh")
  text = text.replace("o.","oh.")
  text = text.replace("o!","oh!")
  text = text.replace("ó ","a")
  text = text.replace("ón ","an")
  ##############################
  text = text.replace("a","#1§")
  text = text.replace("e","#2§")
  text = text.replace("i","#3§")
  text = text.replace("o","#4§")
  text = text.replace("u","#5§")
  text = text.replace("y","#6§")
  text = text.replace("b","#7§")
  text = text.replace("ch","#9§")
  text = text.replace("c","#8§")
  text = text.replace("d","#10§")
  text = text.replace("f","#11§")
  text = text.replace("g","#12§")
  text = text.replace("gu","#13§")
  text = text.replace("gü","#14§")
  text = text.replace("h","#15§")
  text = text.replace("j","#16§")
  text = text.replace("k","#17§")
  text = text.replace("l","#18§")
  text = text.replace("ll","#19§")
  text = text.replace("m","#20§")
  text = text.replace("n","#21§")
  text = text.replace("?","#22§")
  text = text.replace("p","#23§")
  text = text.replace("q","#24§")
  text = text.replace("rr","#26§")
  text = text.replace("r","#25§")
  text = text.replace("s","#27§")
  text = text.replace("t","#28§")
  text = text.replace("v","#29§")
  text = text.replace("w","#30§")
  text = text.replace("x","#31§")
  text = text.replace("z","#32§")
  text = text.replace("á","#33§")
  text = text.replace("é","#34§")
  text = text.replace("í","#35§")
  text = text.replace("ó","#36§")
  text = text.replace("ú","#37§")
  #print("encoding done, now recoding and writing file...")
  text = text.replace("#1§","a")
  text = text.replace("#2§","e")
  text = text.replace("#3§","o")
  text = text.replace("#4§","o")
  text = text.replace("#5§","u")
  text = text.replace("#6§","j")
  text = text.replace("#23§","bb")
  text = text.replace("#7§","b")
  text = text.replace("#8§","zz")
  text = text.replace("#9§","zj")
  text = text.replace("#28§","dd")
  text = text.replace("#10§","d")
  text = text.replace("#11§","vv")
  text = text.replace("#31§","gz")
  text = text.replace("#13§","gw")
  text = text.replace("#14§","gw")
  text = text.replace("#24§","gg")
  text = text.replace("#17§","gg")
  text = text.replace("#12§","g")
  text = text.replace("#15§","h")
  text = text.replace("#16§","x")
  text = text.replace("#19§","lj")
  text = text.replace("#18§","l")
  text = text.replace("#20§","m")
  text = text.replace("#22§","nj")
  text = text.replace("#21§","n")
  text = text.replace("#26§","rr")
  text = text.replace("#25§","r")
  text = text.replace("#27§","z")
  text = text.replace("#29§","v")
  text = text.replace("#30§","w")
  text = text.replace("#32§","z")
  text = text.replace("#33§","ä")
  text = text.replace("#34§","ë")
  text = text.replace("#35§","ö")
  text = text.replace("#36§","ö")
  text = text.replace("#37§","ü")
  ###############################
  text = text.replace("¡","")
  text = text.replace("!","o!")
  text = text.replace("¿","Pu ")
  return text

g = open(sys.argv[1].replace(".txt","") +"_transformed.txt", "a")
f = open(sys.argv[1], "r")
for x in f:
  x=transform(x)
  #print(x)
  x=x.replace("zzz","z")
  g.write(x)
g.close()
